### ISSUE TITLE
[Bug] Unable to select a video

### ISSUE THREAD

**Issue by petlyh** [devhyper/open-video-editor#13]
### Bug description

Pressing the `Select` button to choose a video file opens a screen with the text `Something went wrong` and the Google Play Services icon.

Related question: Does this app depend on Google Play Services?

### Screenshot

<img width="200" src="https://github.com/devhyper/open-video-editor/assets/88139840/1e0d4e89-0f46-4298-90c1-d04c35a0ab85">

### Device/version info

App version: 1.0.1
OS version: Android 8.0 (stock)
Device model: Samsung Galaxy S7 Edge

**Comment by devhyper** [comment]
The app doesn't depend on play services, I believe the play services popup is because play services is trying to provide a fallback for the media picker that is only available on Android 12+. Non play service devices use the fallback provided by AOSP. I'll add a toggle in settings to force a legacy AOSP media picker.

**Comment by devhyper** [comment]
Try this build and let me know if it works:
[app-debug.zip](https://github.com/devhyper/open-video-editor/files/13814856/app-debug.zip)

**Comment by petlyh** [comment]
Thanks for the quick response. The debug build you provided works as expected for me after enabling that option.
