### ISSUE TITLE
Why that massive size increase?

### ISSUE THREAD

**Issue by Freeedim** [devhyper/open-video-editor#65]
Hi everyone,

I tried to explore code and dependencies but I am not proficient enough and could not find the answer by myself.

I just would like to know why v1.1 was around 2 MB while v1.1.1 (supposedly a maintenance or bugfix release) is around 70 MB? I mean, I don't need to know all the precise technical reasons (which I would probably not understand), but just to be reassured that it's something normal, safe and necessary, not an error, a compile-time mistake or so.

**Comment by devhyper** [comment]
> Hi everyone,
> 
> I tried to explore code and dependencies but I am not proficient enough and could not find the answer by myself.
> 
> I just would like to know why v1.1 was around 2 MB while v1.1.1 (supposedly a maintenance or bugfix release) is around 70 MB? I mean, I don't need to know all the precise technical reasons (which I would probably not understand), but just to be reassured that it's something normal, safe and necessary, not an error, a compile-time mistake or so.

The size increase is just because of the addition of the ffmpeg library, which is required to provide functionality not provided with Media3, such as lossless cutting. The next version will reduce the size to ~55 MB since I changed the dependency to the ffmpeg-kit min package, which removes some unneeded stuff.
